ghost_state_machine_node:
  ros__parameters:
    max_linear_vel: 1.65              # m/s

    left_wheel_y:   0.18092
    left_wheel_x:   0.10452
    right_wheel_y:  0.18092
    right_wheel_x:  -0.10452
    back_wheel_x:   -0.209
    back_wheel_y:   0.0

    steering_kp: 0.175

    pose_reset_x_: 0.0
    pose_reset_y_: 0.0
    pose_reset_theta_: 0.0
    pose_reset_x_cov_: 0.0
    pose_reset_y_cov_: 0.0
    pose_reset_theta_cov_: 0.0

    max_motor_rpm_true: 625.0